### ISSUE TITLE
Create pages to handle API error URLs

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#273]
**Original report on BitBucket by sigit nugraha.**

----------------------------------------

The URLs that each of them need to have their own page, explaining the error.

![](https://bitbucket.org/repo/A6bqkay/images/476918484-image.png)
‌

**Comment by MajaDolinar** [comment]
Should this be looked at in the new release? @john-shepherdson 
I do not really understand this issue

**Comment by john-shepherdson** [comment]
This refers to the internal API (i.e. calls made from UI to the backend) not the public API.
As such, it relates to a time when the product was less stable than it is at present, when menu clicks and other one screen actions would result in an error. As this is no longer the case (AFAIK), then this issue is redundant and can be closed.
