### ISSUE TITLE
New workflow: amendments to exports

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#438]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

When I published the first version of the KungPao vocabulary \(SL en and TL fi\):

* the PDF and HTML exports had license logo and license text.

‌

![](https://bitbucket.org/repo/A6bqkay/images/2831271040-image.png)
‌

‌

I created a new version of the TL fi, without SL changing. Published the new version of KungPao vocabulary as SL admin:

* in the new published version, the PDF and HTML exports did not contain license logo and license text.

‌

![](https://bitbucket.org/repo/A6bqkay/images/3985892491-image.png)
‌

‌

So the license logo and text only appear in the first ever published version in the exports.

**Comment by MajaDolinar** [comment]
I am testing this on staging. In editor mode I am trying to export drafts, however export does not work.
Export does not work outside editor also in staging. Please check so that I can test this issue.

**Comment by Stifo** [comment]
* found a bug in export of PDF and HTML for DDI Alliance - fixed, not yet merged in the main branch
* fixed 2.i, 2.ii, and 2.iii - not yet merged in the main

**Comment by Stifo** [comment]
looks like the 1. was already fixed - SL and TL exports contain new codes

**Comment by MajaDolinar** [comment]
Tested on staging for Analysis unit and Aggregation method - the exported pdf did not contain the license logo. All other things noted in this issue are resolved. 
When I do the same on production, the logos are exported - this seems to be an issue only on staging since this logo issues are present throughout the application (see https://vocabularies-staging.cessda.eu). Is this correct @Stifo ?
I believe the exported pdf on production will contain also the license logo? Please correct me if I am wrong, so that I can close this issue.

**Comment by Stifo** [comment]
the problem with logos on dev and stagins is most probably due to missing files in these instances (`/content/images/agency/*.jpg`) as the logo images were probably uploaded to production only. on dev and staging, requesting logo file gives 404 error:

```json
{
    "timestamp": "2023-10-18T11:38:20.155+0000",
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/content/images/agency/44332555-52c2-48f6-8827-c0548d515985.jpg"
}
```

**Comment by john-shepherdson** [comment]
See #796

**Comment by MajaDolinar** [comment]
Issue resolved. Ready for release.
