### ISSUE TITLE
CVs show wrong available from link and do not have Canonical URIs

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#484]
**Original report on BitBucket by Maja Dolinar.**

----------------------------------------

If you go to the CV “CDC Publisher Names” at [https://vocabularies.cessda.eu/vocabulary/CdcPublisherNames?lang=en](https://vocabularies.cessda.eu/vocabulary/CdcPublisherNames?lang=en) and open the tab ‘License and Citation” there is a mistake in 'Available from’ section. See the picture below:

![](https://bitbucket.org/repo/A6bqkay/images/2600135011-image.png)
I tested this for other CVs \(DDI, CESSDA\) and the issue is present everywhere. 

In tab ‘Identity and general’ Canonical URIs are missing everywhere.

‌

The issue was reported from EOSC Helpdesk: [https://eosc-helpdesk.eosc-portal.eu/#ticket/zoom/2197](https://eosc-helpdesk.eosc-portal.eu/#ticket/zoom/2197)

‌

‌

**Comment by Stifo** [comment]
fixed by #526 PR

**Comment by MajaDolinar** [comment]
@Stifo sorry it took so long to answer to this, I was trying to figure this one out and I had a discussion with Taina again. Here are the clarifications:
Currently, the canonical URIs show the version number of the base SL version but this should be changed.
 
**New system:**
- Version number is the same for all languages included in the publication. They are published as one package.
- The canonical URI should show the version number of the whole package, that is, the three-digit version number. Canonical URI is the same for all languages. Actually, languages do not have a separate version number anymore but since CVS has a language-specific display and download functionality, it displays a version number for each language separately but what is displayed is naturally the whole package version number.
- Citations in all languages should show the same canonical URI with the whole package version number
- Not sure how the URL in the citation should be formed but I’m guessing it contains the canonical URI. Are there any Bitbucket issues with the URL? All language citations have the same URL. So maybe like this:
https://vocabularies.cessda.eu/urn/Canonical URI of the vocabulary.

**Previously:**
- At some point, the system had both Canonical URI plus the URI of the version. The canonical URI did not then have a version number and only URI had. This was changed in September 2020 so that there is only Canonical URI and that contains the version number, and URI was removed. See https://bitbucket.org/cessda/cessda.cvs.two/issues/202/remove-canonical-uri-without-version-cvs2
- So I’m not sure if the ‘uri’ has been left unnecessarily somewhere in the code.
- @Stifo Is uri_sl required for any reason anymore as there is no separate URI for SL. Unless it is needed for some workflow issue.
 
The canonical URI is formed from whatever is entered in the Agency information in the element ‘Canonical Uri’, with the version number added to the end. The version number added should be the whole package version number.
Right now the versions in staging in all front-end displays of published vocabularies do not have only one and the same version number everywhere, including a canonical urn, citations, downloads, address lines on top of the page etc across all languages. There should be only one version number everywhere.

**Comment by Stifo** [comment]
Thanks @MajaDolinar, i did it as described. However, we still need to regenerate the citations and update version numbers in it. Could you please a separate issue for that? The canonicalURI and available from show now correct versions. I'm not sure, when the fix appears in the dev/staging after recent migration to github.

FYI: uri and uri_sl is still present in the db and code
